#!/usr/bin/env python3.6

# Authors: Germain Haugou, ETH (germain.haugou@iis.ee.ethz.ch)

 
import json
import argparse
from comp_gen import *


parser = argparse.ArgumentParser(
  description='Generate configuration for Pulp system',
  formatter_class=argparse.RawDescriptionHelpFormatter
)

parser.add_argument("--system", dest="system", default="pulp", help="Specify the chip")

args = parser.parse_args()


system = Component(
    includes=[
        "configs/defaults.json",
        "configs/%s_system.json" % args.system,
        "configs/usecases/jtag.json"
    ]
)

config = system.get_json_config(expand=True)

print (config)
